### ISSUE TITLE
Extending Modern-Business

### ISSUE THREAD

**Issue by StevenBlack** [IronSummitMedia/startbootstrap-modern-business#4]
Hey @davidtmiller I like modern-business so much that I made you a thing.

[A Jekyll-enabled adaptation](https://github.com/StevenBlack/jekyll-modern-business) which you can [see in action here](http://stevenblack.github.io/jekyll-modern-business/).

Right now it's still vanilla.  This is modern-business simply refactored into Jekyll includes and, so far, a single layout.

I plan to extend this further, in a generic way, so Jekyll posts and categories template-into the modern-business *blog home* and *blog post* formats.

Great template, man. :+1: 

*EDIT*: Proper link to  [see in action here](http://stevenblack.github.io/jekyll-modern-business/).

**Comment by davidtmiller** [comment]
Cool, thanks! Once you're finished up with it let me know and I can add it to the user submitted versions on the overview page at Start Bootstrap.
